version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - net
  dynamocl:
    image: yamitzky/dynamodb-gui
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    ports:
      - "8001:8001"
    networks:
      - net
networks:
  net:
    driver: bridge
